
ARG APP
ARG TAG
FROM kalisio/$APP:$TAG
LABEL maintainer="contact@kalisio.xyz"

ARG APP
ARG TEST_REPORTER_VERSION=0.7.0

ENV MOCHA_CONTEXT=$APP
ENV SLACK_WEBOOK_URL=
ENV CC_TEST_REPORTER_ID=

# Install code climate
WORKDIR /opt/kdk/$APP/api
RUN \
  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-${TEST_REPORTER_VERSION}-linux-amd64 > ./cc-reporter && \
  chmod +x ./cc-reporter && \
  mkdir coverage && \
  chmod +w coverage

CMD ./cc-reporter before-build; yarn coverage --reporter test/reporter/reporter.slack; ./cc-reporter format-coverage -t lcov --prefix /opt/kdk/$APP -o coverage/codeclimate.json; ./cc-reporter upload-coverage
