
ARG APP
ARG TAG
FROM kalisio/$APP:$TAG
LABEL maintainer="contact@kalisio.xyz"

ARG APP
ARG TEST_REPORTER_VERSION=0.7.0

# Install code climate
RUN curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-${TEST_REPORTER_VERSION}-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter

ENV MOCHA_CONTEXT=$APP
ENV SLACK_WEBOOK_URL=

WORKDIR /opt/kdk/$APP/api
CMD [ "yarn", "coverage", "--reporter", "test/reporter/reporter.slack" ]
