#
# Build stage
#
FROM  node:8-buster AS Build

ARG APP
ARG BUILD_NUMBER
ARG BRANCH=master

ENV BUILD_NUMBER=$BUILD_NUMBER
ENV NODE_APP_INSTANCE=dev

# Install the cli
WORKDIR /opt
RUN git clone https://github.com/kalisio/kdk.git && cd kdk && yarn 

# Install the app
WORKDIR /opt/kdk
RUN \
  node . kdk/workspaces/${APP}.js --clone && \
  node . kdk/workspaces/${APP}.js --install && \
  node . kdk/workspaces/${APP}.js --link && \
  cd ${APP}\api && yarn build && cd .. && yarn build

#
# Run stage
#
FROM node:8-buster-slim
LABEL maintainer="contact@kalisio.xyz"

ARG APP
ARG BUILD_NUMBER

ENV BUILD_NUMBER=$BUILD_NUMBER
ENV NODE_APP_INSTANCE=dev
ENV DEBUG=kalisio*,-kalisio:kCore:authorisations:hooks

COPY --from=Build /opt/kdk /opt/kdk

WORKDIR /opt/kdk
RUN \
  cd kdk && yarn link && cd .. && \
  node . kdk/workspaces/${APP}.js --link

WORKDIR /opt/kdk/${APP}

EXPOSE 8081
CMD [ "yarn", "prod" ]
