FROM testcafe/testcafe:1.3.3

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

# Increase privileges otherwise we can't write
USER root

# Create a folder holding screenshots
WORKDIR /opt/testcafe
RUN mkdir screenshots && chown user screenshots

WORKDIR /usr/lib/node_modules/testcafe

# Add missing modules for our tests to run
RUN npm install -g testcafe-vue-selectors
#RUN npm install -g mongodb

# Reset privileges
USER user

