FROM testcafe/testcafe:1.3.3

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

WORKDIR /opt/testcafe

# Increase privileges otherwise we can't write
USER root

# Add missing modules for our tests to run
RUN npm install testcafe-vue-selectors
# Create a symlink so that we use the testcafe project as if installed in our test code
RUN cd node_modules && ln -nsf ../ testcafe
# Create a folder holding screenshots
RUN mkdir screenshots
RUN chown user screenshots

# Reset privileges
USER user
