#
# Build stage
#
FROM  node:8-buster AS Build

ARG APP
ARG BUILD_NUMBER
ARG BRANCH=master

ENV BUILD_NUMBER=$BUILD_NUMBER
ENV DEBUG=kalisio*,-kalisio:kCore:authorisations:hooks
ENV NODE_APP_INSTANCE=dev

WORKDIR /opt/${APP}
COPY . /opt/${APP}

WORKDIR /opt/${APP}/modules
RUN git clone https://github.com/kalisio/kCore.git -b ${BRANCH} --single-branch && cd kCore && yarn && yarn link && cd ..

WORKDIR /opt/${APP}/api
RUN \
  yarn && \
  yarn link @kalisio/kdk-core && \
  yarn build

WORKDIR /opt/${APP}
RUN \
  yarn && \
  yarn link @kalisio/kdk-core && \
  yarn build

#
# Release stage
#
FROM node:8-buster-slim
LABEL maintainer="contact@kalisio.xyz"

ARG APP

COPY --from=Build /opt/${APP} /opt/${APP}

RUN ls /opt/${APP} && ls /opt/${APP}/modules

WORKDIR /opt/${APP}/modules
RUN cd kCore && yarn link

WORKDIR /opt/${APP}/api
RUN yarn link @kalisio/kdk-core

WORKDIR /opt/${APP}
RUN yarn link @kalisio/kdk-core

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
