#
# Build stage
#
FROM  node:8-buster AS Build

ARG APP
ARG BUILD_NUMBER

ENV BUILD_NUMBER=$BUILD_NUMBER
ENV NODE_APP_INSTANCE=test

WORKDIR /opt/${APP}
COPY . /opt/${APP}

WORKDIR /opt/${APP}/modules
RUN git clone https://github.com/kalisio/kCore.git -b test --single-branch && cd kCore && yarn && yarn link && cd ..

WORKDIR /opt/${APP}/api
RUN \
  yarn && \
  yarn link @kalisio/kdk-core && \
  yarn build

WORKDIR /opt/${APP}
RUN \
  yarn && \
  yarn link @kalisio/kdk-core && \
  yarn build

#
# Run stage
#
FROM node:8-buster-slim
LABEL maintainer="contact@kalisio.xyz"

ARG APP
ARG BUILD_NUMBER

ENV BUILD_NUMBER=$BUILD_NUMBER
ENV NODE_APP_INSTANCE=test
ENV DEBUG=kalisio*,-kalisio:kCore:authorisations:hooks

COPY --from=Build /opt/${APP} /opt/${APP}

WORKDIR /opt/${APP}/modules
RUN cd kCore && yarn link

WORKDIR /opt/${APP}/api
RUN yarn link @kalisio/kdk-core

WORKDIR /opt/${APP}
RUN yarn link @kalisio/kdk-core

EXPOSE 8081

CMD [ "yarn", "prod" ]