name: Build docs
on:
  push:
    branches:
      - gha
jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      # - name: Cache requirements
      #   uses: actions/cache@v4
      #   with:
      #     key: requirements
      #     path: ${{ runner.temp }}/dl
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      # - uses: actions/cache@v4
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          GITHUB_DEVELOPMENT_PAT: ${{ secrets.GH_DEVELOPMENT_PAT }}
        run: bash ./scripts/setup_workspace.sh -k nokli
      - name: Build docs
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/build_docs.sh -p -r
